name: $(Build.BuildID)
resources:
- repo: self

phases:
- phase: Windows_Phase
  displayName: Windows
  condition: succeeded()
  queue:
    name: Hosted Windows 2019 with VS2019

  steps:
  - powershell: |
       # Build the module and help
       .\Build-Module.ps1 -buildHelp

    displayName: 'Build Module'

  - task: CopyFiles@2
    displayName: 'Copy Module to Artifacts Folder'
    inputs:
      Contents: |
       README.md
       .gitignore
       dist\**
      TargetFolder: '$(build.artifactstagingdirectory)/VSTeam'
      flattenFolders: false
    condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], false))

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Module'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/VSTeam'
      ArtifactName: 'Module'
      publishLocation: 'Container'
    condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], false))

  - task: CopyFiles@2
    displayName: 'Copy Integration Tests Artifacts Folder'
    inputs:
      Contents: |
       dist\*.psd1
       integration\**

      TargetFolder: '$(build.artifactstagingdirectory)/Tests'
    condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], false))

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Tests'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/Tests'
      ArtifactName: Test
      publishLocation: 'Container'
    condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], false))
