#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: '3'
services: 
 
  ubuntu:
      stdin_open: true
      tty: true
      # Uncomment the next line to use a non-root user for all processes. 
      # user: vscode

      build:
        context: .
        dockerfile: linux/Dockerfile

      volumes:
        # Update this to wherever you want VS Code to mount the folder of your project
        - ./../:c:/vsteam

      # Overrides default command so things don't shut down after the process ends.
      command: >
          pwsh "cd 'c:/vsteam'; ./Build-Module.ps1 -runTests"

  wcore1903:
      stdin_open: true
      tty: true
      # Uncomment the next line to use a non-root user for all processes. 
      # user: vscode

      build:
        context: .
        dockerfile: wcore1903/Dockerfile

      volumes:
        # Update this to wherever you want VS Code to mount the folder of your project
        - ./../:c:/vsteam

      # Overrides default command so things don't shut down after the process ends.
      command: >
          powershell "cd 'c:/vsteam'; ./Build-Module.ps1 -runTests"